#!/bin/sh

for tf in 94 90 80 70 60 50; do
    echo ">> $tf"
    sed -i "s/-0\.[0-9]\+D0)!!!/-0.${tf}D0)!!!/" vmcw_st.f
    make vmcw_st
    sed -i "s/tf0[0-9]\+\.dat/tf0${tf}.dat/" vmcw.cmd
    ./vmcw_st
done
